port: /dev/ttyUSB0
rate: 5
joints: {
    servo1_joint: {id: 1, invert: True, max_angle: 10, min_angle: -90},
    servo2_joint: {id: 2, max_angle: 10, min_angle: -90},
    servo3_joint: {id: 3, max_angle: -70, min_angle: -110},
    servo4_joint: {id: 4, max_angle: 50, min_angle: -70},
    servo5_joint: {id: 5, max_angle: 20, min_angle: -50},
    servo6_joint: {id: 6, max_angle: 150, min_angle: -150}
}

